"""
Django settings for EpCouncil project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@8)8^r^dvmx&!1tob28g!4br*&!&z8d+9xsfpvabsk#lfqu2@9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Application',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EpCouncil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EpCouncil.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]

STATIC_ROOT = os.path.join(BASE_DIR,'assets')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TIME_ZONE = 'Africa/Kigali'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

JAZZMIN_SETTINGS = {
    # General settings
    "site_title": "Epworth Admin",
    "site_header": "Epworth Council Admin",
    "site_brand": "Epworth Council",
    "site_logo": "img/eplims.png",  # Remove "static\" prefix
    "welcome_sign": "Welcome to the Epworth Admin Panel",
    "copyright": "Epworth Council",  # Copyright footer text
    
    # UI Customization
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "show_ui_builder": True,  # Enables UI theme switcher in admin
    
    # Theme options
    "theme": "darkly",  # Try: darkly, flatly, simplex, etc.
    "dark_mode_theme": "darkly",
    
    # Icons configuration
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "your_app.House": "fas fa-home",
    },
    
    # Top menu configuration
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://example.com/support", "new_window": True},
        {"model": "auth.User"},  # App with dropdown to all its models pages
    ],
    
    # Custom CSS/JS
    "custom_css": "css/admin_custom.css",  # Path to custom CSS file
    "custom_js": "js/admin_custom.js",     # Path to custom JS file
    
    # Additional UI tweaks
    "changeform_format": "horizontal_tabs",  # horizontal_tabs/collapsible/vertical_tabs
    "related_modal_active": True,  # Use modals for related fields
    "use_google_fonts_cdn": True,  # Use Google fonts
    
    # Search bar configuration
    "search_model": ["auth.User", "your_app.House"],
    
    # Custom links
    "additional_footer_links": {
        "Epworth Website": "https://www.epworthcouncil.org",
        "Documentation": "https://example.com/docs",
    },
}