# Generated by Django 5.2.2 on 2025-06-13 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('well_depth', models.DecimalField(decimal_places=2, help_text='Depth of the well in meters', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('well_diameter', models.DecimalField(decimal_places=2, help_text='Diameter of the well in centimeters', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('is_potable', models.BooleanField(default=False, help_text='Whether the water is safe for drinking')),
                ('daily_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Daily water yield in liters', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Houses with Wells',
                'ordering': ['address'],
            },
        ),
    ]
